# This script makes plots from the SIF retrievals generated by the Matlab scripts from Frankenberg, specifically
# the Run_Frankenberg_scripts.m master script.  This script is based on a similar script for plotting the results
# of the SFM retrieval, called SFMresults_summary.R. This script generates warnings during ggsave calls: 
# "Removed 171 row(s) containing missing values (geom_path)." These warnings are for the plots of high sif scenarios
# (SIF level 3 from 2_make_stray_light_simulations_v2.R) because the y-axis limits were set for the lower SIF level
# used for the main text results (SIF level 2 from 2_make_stray_light_simulations_v2.R).
#
# Contact: Loren Albert, lalbert@email.arizona.edu; loren.albert@mail.wvu.edu
# Here were the scenarios used for SFM retrieval:
#
#
# Copyright (C) 2022  Loren Albert
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
# and associated documentation files (the "Software"), to deal in the Software without restriction, 
# including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
# and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial 
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
# NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#
#
# Inputs: the results of SIF retrieval from Frankenberg's code, which uses SVD. Those are Matlab scripts. The
# master script is Run_Frankenberg_scripts.m
#
## Here are the scenarios I used for retrieval:
# No spectral stray light scenario
# 1) Solar_no_SL.csv paired with Vegetation_no_SL_SIFl1.csv (SIF ~ 1mW @ 760 nm)
# 2) Solar_no_SL.csv paired with Vegetation_no_SL_SIFl2.csv (SIF ~ 2mW @ 760 nm)
# 3) Solar_no_SL.csv paired with Vegetation_no_SL_SIFl3.csv (SIF ~ 3mW @ 760 nm)
# 
# Low spectral stray light scenario
# 4) Solar_SL_Dmat_scenario4.csv paired with Vegetation_SL_Dmat_scenario4_SIFl1.csv (SIF ~ 1mW @ 760 nm)
# 5) Solar_SL_Dmat_scenario4.csv paired with Vegetation_SL_Dmat_scenario4_SIFl2.csv (SIF ~ 2mW @ 760 nm)
# 6) Solar_SL_Dmat_scenario4.csv paired with Vegetation_SL_Dmat_scenario4_SIFl3.csv (SIF ~ 3mW @ 760 nm)
# 
# Medium spectral stray light scenario
# 7) Solar_SL_Dmat_scenario3.csv paired with Vegetation_SL_Dmat_scenario3.csv_SIFl1.csv (SIF ~ 1mW @ 760 nm)
# 8) Solar_SL_Dmat_scenario3.csv paired with Vegetation_SL_Dmat_scenario3.csv_SIFl2.csv (SIF ~ 2mW @ 760 nm)
# 9) Solar_SL_Dmat_scenario3.csv paired with Vegetation_SL_Dmat_scenario3.csv_SIFl3.csv (SIF ~ 3mW @ 760 nm)
# 
# High spectral stray light scenario
# 10) Solar_SL_Dmat_scenario2.csv paired with Vegetation_SL_Dmat_scenario2.csv_SIFl1.csv (SIF ~ 1mW @ 760 nm)
# 11) Solar_SL_Dmat_scenario2.csv paired with Vegetation_SL_Dmat_scenario2.csv_SIFl2.csv (SIF ~ 2mW @ 760 nm)
# 12) Solar_SL_Dmat_scenario2.csv paired with Vegetation_SL_Dmat_scenario2.csv_SIFl3.csv (SIF ~ 3mW @ 760 nm)
# 
# Very High spectral stray light scenario
# 13) Solar_SL_Dmat_scenario1.csv paired with Vegetation_SL_Dmat_scenario1_SIFl1.csv (SIF ~ 1mW @ 760 nm)
# 14) Solar_SL_Dmat_scenario1.csv paired with Vegetation_SL_Dmat_scenario1_SIFl2.csv (SIF ~ 2mW @ 760 nm)
# 15) Solar_SL_Dmat_scenario1.csv paired with Vegetation_SL_Dmat_scenario1_SIFl3.csv (SIF ~ 3mW @ 760 nm)

# # Luis' instructions about the columns of the data (shows that they correspond to the scenario numbers above)
# scenario1 correspond to VERY HIGH SL (13-15),
# scenario2 correspond to HIGH SL (10-12),
# scenario3 correspond to MEDIUM SL (7-9),
# and scenario4 to LOW SL (4-6)

#
#
# Copyright (C) 2022  Loren Albert.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.




## Housekeeping--------------------------------------------------------------
## Remove workspace objects if necessary
# rm(list=ls())

require(ncdf4)
require(ggplot2)
require(viridis)
library(htmlTable)

## Change working directory if necessary
# setwd('/Users/lalbert/Dropbox (Brown)/CFL_002_calib paper/Stray light simulations paper/SL_SIF_analysis_repo/')


## define paths
path_figs <- "./Figures/"
path_spectra <- "./Outputs/"
path_data_LL <- "./Inputs/"
path_inputs <- "./Inputs/"

## Import fluoresence shape (F_true) for stray light error calculation and plots
SIF_true_SIFl3 <- read.csv(paste(path_spectra, "SIF_SIFl3.csv", sep = ""))
SIF_true_SIFl3 <- SIF_true_SIFl3[,1]
SIF_true_SIFl2 <- read.csv(paste(path_spectra, "SIF_SIFl2.csv", sep = ""))
SIF_true_SIFl2 <- SIF_true_SIFl2[,1]
SIF_true_SIFl1 <- read.csv(paste(path_spectra, "SIF_SIFl1.csv", sep = ""))
SIF_true_SIFl1 <- SIF_true_SIFl1[,1]

## Import Wavelength values for each spectral pixel
Wavelengths <- read.csv(paste(path_data_LL,"predicted_spectral_pixels_2018.csv",sep=""))

## Import SVD SIF retrieval results
SVD_SIF <- read.csv(paste(path_inputs, "SIF_SVD_farRed.csv", sep = ""))

## Define fit range (this was defined in the fitAllFR matlab script that was part of the retrieval process)
FR_ind = 1530:1700


### Plots ---------------------------------------------------------------------

## Set working directory
# setwd(path_figs)

## choose x-values for entire instrument range
xVals <- Wavelengths[,2]

## choose y limits (good to coordinate with ylimits for 3FLD in make_stray_light_simulations_v2.R)
#sif_ylim <- c(-.002, max(SIF_true_SIFl3) + 0.0005) # Range from previous submission
sif_ylim <- c(-.0001, (max(SIF_true_SIFl2) + 0.0005)) # This range works well for SIF level 1 and 2, 
                                                      # but throws warning for SIF l3 because it doesn't show highest values


## Quick plot of all scenarios
viridis_cols <- viridis(15)
plot(FR_ind, rep(SVD_SIF[1,2], length(FR_ind)), type = "l")
for(i in 1:15){
  plot(FR_ind, rep(SVD_SIF[i,2], length(FR_ind)), col = viridis_cols[i], ylim = c(0,0.0045))
}

## Define color palette
colsRetStray <- c("SVD with stray"="#DAC228","SVD no stray"="#122B5D","Simulated SIF"="black")

## Define text for use in graphs
radiance_text = expression('Radiance (W m'^"-2"*' sr'^"-1"*' nm'^"-1"*')')
radiance_text_log = expression('Log Radiance (W m'^"-2"*' sr'^"-1"*' nm'^"-1"*')')
radiance_text_error = expression('Stray light error (W m'^"-2"*' sr'^"-1"*' nm'^"-1"*')')
radiance_text_error = expression(atop('Stray light error', paste('(W m'^"-2"*' sr'^"-1"*' nm'^"-1"*')')))

# Define function to make plot of SIF true, SIF retrieved w/o stray light, and SIF retrieved in presence of SL
plot_SIF <- function(SIF_true_level, no_SL_scenario, SL_scenario){
  
  no_SL_scenario_vec <- rep(no_SL_scenario, length(FR_ind))
  SL_scenario_vec <- rep(SL_scenario, length(FR_ind))
  
  sif_plot <- ggplot() +
    # SIF spectrum
    geom_line(data = data.frame(x = xVals, y = SIF_true_level), aes(x=x, y=y, colour = "Simulated SIF"), alpha = 0.45, size = 1) +
    # Retrieved SIF without stray light
    geom_line(data = data.frame(x = Wavelengths$spec_pixel_pred_no710[FR_ind], y = no_SL_scenario_vec), aes(x=x, y=y, colour = "SVD no stray"), 
              alpha = 0.75, size = 1) +
    # Retrieved SIF with stray light in far-red region
    geom_line(data = data.frame(x = Wavelengths$spec_pixel_pred_no710[FR_ind], y = SL_scenario_vec), aes(x=x, y=y, colour = "SVD with stray"), 
              alpha = 0.70, size = 1) +
    theme_classic() +
    scale_x_continuous(limits = c(669, 781), breaks=seq(670,780,20), expand = c(0, 0)) +
    scale_y_continuous(limits = sif_ylim) +
    xlab("Wavelength (nm)") +
    ylab(radiance_text) +
    scale_colour_manual(values=colsRetStray, name = "") +
    theme(legend.position="none") + 
    geom_hline(yintercept = 0, linetype = "solid", color = "black", size = 0.3)
  
  sif_plot
  
}

## Plot SVD SIF

# Very high stray light scenario (Low SIF (SIFl1))
SIFl1_ret_SVD_Dmat_1 <- plot_SIF(SIF_true_level = SIF_true_SIFl1, no_SL_scenario = SVD_SIF[1,2], SL_scenario = SVD_SIF[13,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_1_SIFl1.pdf",sep = ""),
       plot = SIFl1_ret_SVD_Dmat_1, width = 10, height = 6, units = "cm", dpi = 300)

# Very high stray light scenario (Mid SIF (SIFl2))
SIFl2_ret_SVD_Dmat_1 <- plot_SIF(SIF_true_level = SIF_true_SIFl2, no_SL_scenario = SVD_SIF[2,2], SL_scenario = SVD_SIF[14,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_1_SIFl2.pdf",sep = ""),
       plot = SIFl2_ret_SVD_Dmat_1, width = 10, height = 6, units = "cm", dpi = 300)

# Very high stray light scenario (High SIF (SIFl3))
SIFl3_ret_SVD_Dmat_1 <- plot_SIF(SIF_true_level = SIF_true_SIFl3, no_SL_scenario = SVD_SIF[3,2], SL_scenario = SVD_SIF[15,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_1_SIFl3.pdf",sep = ""),
       plot = SIFl3_ret_SVD_Dmat_1, width = 10, height = 6, units = "cm", dpi = 300)

# High stray light scenario (Low SIF (SIFl1))
SIFl1_ret_SVD_Dmat_2 <- plot_SIF(SIF_true_level = SIF_true_SIFl1, no_SL_scenario = SVD_SIF[1,2], SL_scenario = SVD_SIF[10,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_2_SIFl1.pdf",sep = ""),
       plot = SIFl1_ret_SVD_Dmat_2, width = 10, height = 6, units = "cm", dpi = 300)

# High stray light scenario (Mid SIF (SIFl2))
SIFl2_ret_SVD_Dmat_2 <- plot_SIF(SIF_true_level = SIF_true_SIFl2, no_SL_scenario = SVD_SIF[2,2], SL_scenario = SVD_SIF[11,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_2_SIFl2.pdf",sep = ""),
       plot = SIFl2_ret_SVD_Dmat_2, width = 10, height = 6, units = "cm", dpi = 300)

# High stray light scenario (High SIF (SIFl3))
SIFl3_ret_SVD_Dmat_2 <- plot_SIF(SIF_true_level = SIF_true_SIFl3, no_SL_scenario = SVD_SIF[3,2], SL_scenario = SVD_SIF[12,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_2_SIFl3.pdf",sep = ""),
       plot = SIFl3_ret_SVD_Dmat_2, width = 10, height = 6, units = "cm", dpi = 300)

# Medium stray light scenario (Low SIF (SIFl1))
SIFl1_ret_SVD_Dmat_3 <- plot_SIF(SIF_true_level = SIF_true_SIFl1, no_SL_scenario = SVD_SIF[1,2], SL_scenario = SVD_SIF[7,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_3_SIFl1.pdf",sep = ""),
       plot = SIFl1_ret_SVD_Dmat_3, width = 10, height = 6, units = "cm", dpi = 300)

# Medium stray light scenario (Mid SIF (SIFl2))
SIFl2_ret_SVD_Dmat_3 <- plot_SIF(SIF_true_level = SIF_true_SIFl2, no_SL_scenario = SVD_SIF[2,2], SL_scenario = SVD_SIF[8,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_3_SIFl2.pdf",sep = ""),
       plot = SIFl2_ret_SVD_Dmat_3, width = 10, height = 6, units = "cm", dpi = 300)

# Medium stray light scenario (High SIF (SIFl3))
SIFl3_ret_SVD_Dmat_3 <- plot_SIF(SIF_true_level = SIF_true_SIFl3, no_SL_scenario = SVD_SIF[3,2], SL_scenario = SVD_SIF[9,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_3_SIFl3.pdf",sep = ""),
       plot = SIFl3_ret_SVD_Dmat_3, width = 10, height = 6, units = "cm", dpi = 300)

# Low stray light scenario (Low SIF (SIFl1))
SIFl1_ret_SVD_Dmat_4 <- plot_SIF(SIF_true_level = SIF_true_SIFl1, no_SL_scenario = SVD_SIF[1,2], SL_scenario = SVD_SIF[4,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_4_SIFl1.pdf",sep = ""),
       plot = SIFl1_ret_SVD_Dmat_4, width = 10, height = 6, units = "cm", dpi = 300)

# Low stray light scenario (Mid SIF (SIFl2))
SIFl2_ret_SVD_Dmat_4 <- plot_SIF(SIF_true_level = SIF_true_SIFl2, no_SL_scenario = SVD_SIF[2,2], SL_scenario = SVD_SIF[5,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_4_SIFl2.pdf",sep = ""),
       plot = SIFl2_ret_SVD_Dmat_4, width = 10, height = 6, units = "cm", dpi = 300)

# Low stray light scenario (High SIF (SIFl3))
SIFl3_ret_SVD_Dmat_4 <- plot_SIF(SIF_true_level = SIF_true_SIFl3, no_SL_scenario = SVD_SIF[3,2], SL_scenario = SVD_SIF[6,2])
ggsave(filename = paste(path_figs,"Fig_SVD_SIF_ret_Dmat_4_SIFl3.pdf",sep = ""),
       plot = SIFl3_ret_SVD_Dmat_4, width = 10, height = 6, units = "cm", dpi = 300)


### Calculate differences between scenarios with and w/o stray light ---------------------------

# Calculate difference between corresponding scenarios

SVD_SL_Dmat_1_SIFl1_diff <- SVD_SIF[13,2] - SVD_SIF[1,2]
SVD_SL_Dmat_1_SIFl2_diff <- SVD_SIF[14,2] - SVD_SIF[2,2]
SVD_SL_Dmat_1_SIFl3_diff <- SVD_SIF[15,2] - SVD_SIF[3,2]
SVD_SL_Dmat_2_SIFl1_diff <- SVD_SIF[10,2] - SVD_SIF[1,2]
SVD_SL_Dmat_2_SIFl2_diff <- SVD_SIF[11,2] - SVD_SIF[2,2]
SVD_SL_Dmat_2_SIFl3_diff <- SVD_SIF[12,2] - SVD_SIF[3,2]
SVD_SL_Dmat_3_SIFl1_diff <- SVD_SIF[7,2] - SVD_SIF[1,2]
SVD_SL_Dmat_3_SIFl2_diff <- SVD_SIF[8,2] - SVD_SIF[2,2]
SVD_SL_Dmat_3_SIFl3_diff <- SVD_SIF[9,2] - SVD_SIF[3,2]
SVD_SL_Dmat_4_SIFl1_diff <- SVD_SIF[4,2] - SVD_SIF[1,2]
SVD_SL_Dmat_4_SIFl2_diff <- SVD_SIF[5,2] - SVD_SIF[2,2]
SVD_SL_Dmat_4_SIFl3_diff <- SVD_SIF[6,2] - SVD_SIF[3,2]

# Combine the differences between scenarios with and without stray light into a dataframe
SVD_diffs <- data.frame(cbind(Wavelengths[FR_ind ,2],
                              SVD_SL_Dmat_1_SIFl1_diff,
                              SVD_SL_Dmat_1_SIFl2_diff,
                              SVD_SL_Dmat_1_SIFl3_diff,
                              SVD_SL_Dmat_2_SIFl1_diff,
                              SVD_SL_Dmat_2_SIFl2_diff,
                              SVD_SL_Dmat_2_SIFl3_diff,
                              SVD_SL_Dmat_3_SIFl1_diff,
                              SVD_SL_Dmat_3_SIFl2_diff,
                              SVD_SL_Dmat_3_SIFl3_diff,
                              SVD_SL_Dmat_4_SIFl1_diff,
                              SVD_SL_Dmat_4_SIFl2_diff,
                              SVD_SL_Dmat_4_SIFl3_diff))


### Calculate error as a proportion of SIF --------------------------------------------------------------

# Calculate error as a proportion of SIF_true (called 'SIF_2perc' in make_stray_light_simulations_v2.R)
# With SL minus w/o SL divided by SIF_true, for all SL and SIF level scenarios
SVD_SL_Dmat_1_SIFl1_diff <- (SVD_SIF[13,2] - SVD_SIF[1,2])
SVD_SL_Dmat_1_SIFl1_error <- rep(SVD_SL_Dmat_1_SIFl1_diff, length(FR_ind))/SIF_true_SIFl1[FR_ind]
SVD_SL_Dmat_1_SIFl2_diff <- (SVD_SIF[14,2] - SVD_SIF[2,2])
SVD_SL_Dmat_1_SIFl2_error <- rep(SVD_SL_Dmat_1_SIFl2_diff, length(FR_ind))/SIF_true_SIFl2[FR_ind]
SVD_SL_Dmat_1_SIFl3_diff <- (SVD_SIF[15,2] - SVD_SIF[3,2])
SVD_SL_Dmat_1_SIFl3_error <- rep(SVD_SL_Dmat_1_SIFl3_diff, length(FR_ind))/SIF_true_SIFl3[FR_ind]

SVD_SL_Dmat_2_SIFl1_diff <- (SVD_SIF[10,2] - SVD_SIF[1,2])
SVD_SL_Dmat_2_SIFl1_error <- rep(SVD_SL_Dmat_2_SIFl1_diff, length(FR_ind))/SIF_true_SIFl1[FR_ind]
SVD_SL_Dmat_2_SIFl2_diff <- (SVD_SIF[11,2] - SVD_SIF[2,2])
SVD_SL_Dmat_2_SIFl2_error <- rep(SVD_SL_Dmat_2_SIFl2_diff, length(FR_ind))/SIF_true_SIFl2[FR_ind]
SVD_SL_Dmat_2_SIFl3_diff <- (SVD_SIF[12,2] - SVD_SIF[3,2])
SVD_SL_Dmat_2_SIFl3_error <- rep(SVD_SL_Dmat_2_SIFl3_diff, length(FR_ind))/SIF_true_SIFl3[FR_ind]

SVD_SL_Dmat_3_SIFl1_diff <- (SVD_SIF[7,2] - SVD_SIF[1,2])
SVD_SL_Dmat_3_SIFl1_error <- rep(SVD_SL_Dmat_3_SIFl1_diff, length(FR_ind))/SIF_true_SIFl1[FR_ind]
SVD_SL_Dmat_3_SIFl2_diff <- (SVD_SIF[8,2] - SVD_SIF[2,2])
SVD_SL_Dmat_3_SIFl2_error <- rep(SVD_SL_Dmat_3_SIFl2_diff, length(FR_ind))/SIF_true_SIFl2[FR_ind]
SVD_SL_Dmat_3_SIFl3_diff <- (SVD_SIF[9,2] - SVD_SIF[3,2])
SVD_SL_Dmat_3_SIFl3_error <- rep(SVD_SL_Dmat_3_SIFl3_diff, length(FR_ind))/SIF_true_SIFl3[FR_ind]

SVD_SL_Dmat_4_SIFl1_diff <- (SVD_SIF[4,2] - SVD_SIF[1,2])
SVD_SL_Dmat_4_SIFl1_error <- rep(SVD_SL_Dmat_4_SIFl1_diff, length(FR_ind))/SIF_true_SIFl1[FR_ind]
SVD_SL_Dmat_4_SIFl2_diff <- (SVD_SIF[5,2] - SVD_SIF[2,2])
SVD_SL_Dmat_4_SIFl2_error <- rep(SVD_SL_Dmat_4_SIFl2_diff, length(FR_ind))/SIF_true_SIFl2[FR_ind]
SVD_SL_Dmat_4_SIFl3_diff <- (SVD_SIF[6,2] - SVD_SIF[3,2])
SVD_SL_Dmat_4_SIFl3_error <- rep(SVD_SL_Dmat_4_SIFl3_diff, length(FR_ind))/SIF_true_SIFl3[FR_ind]


### Make table --------------------------------------------------------------

# Combine the stray light errors as a proportion of SIF into a dataframe
SVD_error_prop_to_SIF <- data.frame(cbind(Wavelengths[FR_ind, 2],
                                          SVD_SL_Dmat_1_SIFl1_error,
                                          SVD_SL_Dmat_1_SIFl2_error,
                                          SVD_SL_Dmat_1_SIFl3_error,
                                          SVD_SL_Dmat_2_SIFl1_error,
                                          SVD_SL_Dmat_2_SIFl2_error,
                                          SVD_SL_Dmat_2_SIFl3_error,
                                          SVD_SL_Dmat_3_SIFl1_error,
                                          SVD_SL_Dmat_3_SIFl2_error,
                                          SVD_SL_Dmat_3_SIFl3_error,
                                          SVD_SL_Dmat_4_SIFl1_error,
                                          SVD_SL_Dmat_4_SIFl2_error,
                                          SVD_SL_Dmat_4_SIFl3_error))

# Define row indices for SIFl2
SIFl2_ind <- c(1, 3, 6, 9, 12)
# Define row indices for SIFl1 (for supplement)
SIFl1_ind <- c(1, 2, 5, 8, 11)
# Define row indices for SIFl3 (for supplement)
SIFl3_ind <- c(1, 4, 7, 10, 13)

# Define column indices for values (increments) to show along the length of the far-red index
# 171/ 34 is 5 
wave_indices <- seq(1, 171, 34)

# Take the SIFl2 and index by the wavelength indices and SIF levels I want to show in the results table
SVD_stray_summary_table <- SVD_error_prop_to_SIF[wave_indices, SIFl2_ind]
# Take the SIFl1, SIFl2, and SIFl3 and index by the O2A and O2B bands to make larger results table for supplement
SVD_stray_summary_table_supplement_SIFl1 <- SVD_error_prop_to_SIF[wave_indices, SIFl1_ind] 
SVD_stray_summary_table_supplement_SIFl3 <- SVD_error_prop_to_SIF[wave_indices, SIFl3_ind]

# Convert from proportion to percentage for the table
SVD_stray_summary_table_perc <- SVD_stray_summary_table * 100
SVD_stray_summary_table_supplement_SIFl1_perc <- SVD_stray_summary_table_supplement_SIFl1 * 100
SVD_stray_summary_table_supplement_SIFl3_perc <- SVD_stray_summary_table_supplement_SIFl3 * 100

# Transpose and organize
SVD_stray_summary_table_perc_cols <- t(SVD_stray_summary_table_perc[ , 2:ncol(SVD_stray_summary_table_perc)])
SVD_stray_summary_table_supplement_SIFl1_perc_cols <- t(SVD_stray_summary_table_supplement_SIFl1_perc[ ,2:ncol(SVD_stray_summary_table_supplement_SIFl1_perc)])
SVD_stray_summary_table_supplement_SIFl3_perc_cols <- t(SVD_stray_summary_table_supplement_SIFl3_perc[ ,2:ncol(SVD_stray_summary_table_supplement_SIFl3_perc)])
SVD_stray_summary_table_supplement_perc_cols <- rbind(SVD_stray_summary_table_supplement_SIFl1_perc_cols,
                                                      SVD_stray_summary_table_perc_cols,
                                                      SVD_stray_summary_table_supplement_SIFl3_perc_cols)

# Make table for results
# Main text
htmlTable(round(SVD_stray_summary_table_perc_cols, digits = 2), 
          header =  as.character(round(SVD_stray_summary_table[ ,1], digits = 2)),
          rnames = paste("Scenario ", as.character(rep(c(1,2,3,4), times = 2)), "orders of magnitude"))
# Supplementary table with all three SIF levels
htmlTable(round(SVD_stray_summary_table_supplement_perc_cols, digits = 2),
          header =  as.character(round(SVD_stray_summary_table[ ,1], digits = 2)),
          rnames = paste("Scenario ", as.character(rep(c(1,2,3,4), times = 3)), "orders of magnitude"))


### Export differences and errors as proportion of SIF (for synthesis with other retrieval methods in a new plot) --------------------------------------------------

write.table(SVD_diffs, file = paste(path_spectra, "SVD_stray_no_stray_differences.csv", sep = ""), row.names = FALSE, sep = ",")

write.table(SVD_error_prop_to_SIF, file = paste(path_spectra, "SVD_errors_prop_to_SIF.csv", sep = ""), row.names = FALSE, sep = ",")

